### ISSUE TITLE
Upload to docker hub

### ISSUE THREAD

**Issue by madhogs** [erri120/docker-caddy-porkbun#1]
Hi,
Would you consider uploading this to docker hub? I don't think there is a pre-made caddy container for porkbun on docker hub yet.
Thanks

**Comment by erri120** [comment]
https://hub.docker.com/r/erri120/docker-caddy-porkbun/tags

**Comment by madhogs** [comment]
That was very fast, thank you!

Would you be able to add the arm64 arch as well? Was hoping to use this on a 64 bit raspberry pi.

**Comment by erri120** [comment]
I'm surprised anyone else is interested in this at all, I'm running this container in WSL 2 and on my Raspberry Pi 2 (armv7) but I can also add `linux/arm64`.
